apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  GRAPH_CLIENT_ID: {{ .Values.GRAPH_CLIENT_ID | quote }}
  GRAPH_TENANT_ID: {{ .Values.GRAPH_TENANT_ID | quote }}
  GRAPH_APP_SCOPES: {{ .Values.GRAPH_APP_SCOPES | quote }}
  DB_PORT: {{ .Values.DB_PORT | quote }}
  DB_HOST: {{ .Values.DB_HOST | quote }}
  DB_NAME: {{ .Values.DB_NAME | quote }}
  WEBHOOK_LISTEN_IP: {{ .Values.WEBHOOK_LISTEN_IP | quote }}
  WEBHOOK_LISTEN_PORT: {{ .Values.WEBHOOK_LISTEN_PORT | quote }}
  WEBHOOK_EXTERNAL_BASE_URL: "https://{{ (index .Values.ingress.hosts 0).host }}"
  LOG_LEVEL: {{ .Values.LOG_LEVEL | quote }}
  GOOSE_DRIVER: {{ .Values.GOOSE_DRIVER | quote }}
  GOOSE_MIGRATION_DIR: {{ .Values.GOOSE_MIGRATION_DIR | quote }}
  GOOSE_TABLE: {{ .Values.GOOSE_TABLE | quote }}
